spring.application.name=jkconverter

# PORT dynamique pour Render
server.port=8080

# CONFIGURATION JSP
spring.mvc.view.prefix=/WEB-INF/jsp/
spring.mvc.view.suffix=.jsp

# DESACTIVER LA PAGE PAR DEFAUT
spring.mvc.welcome-page-handler.enabled=false

# TAILLE DES FICHIERS
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB

# PERFORMANCE DEV
spring.web.resources.cache.period=0